version: '3'
services:
  example:
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    image: example
    command: uvicorn example.main:app --port 8000 --host 0.0.0.0
#  redis:
#    hostname: redis
#    image: redis
#    volumes:
#      - ./redis/data:/data
#  postgres:
#    hostname: postgres
#    image: postgres
#    privileged: true
#    volumes:
#      - ./pg_data/data:/var/lib/postgresql/data/pgdata
